// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shiftVec
NumericVector shiftVec(NumericVector elv, NumericVector vid);
RcppExport SEXP tergmLite_shiftVec(SEXP elvSEXP, SEXP vidSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type elv(elvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vid(vidSEXP);
    __result = Rcpp::wrap(shiftVec(elv, vid));
    return __result;
END_RCPP
}
